ALTER TABLE PROD_DM_MARKUP_TAB DROP CONSTRAINT FK_PROD_DM_MARKUP_TAB38
/
ALTER TABLE PROD_DM_MARKUP_TAB DROP CONSTRAINT FK_PROD_DM_MARKUP_TAB37
/
ALTER TABLE PROD_DM_FILE_TAB DROP CONSTRAINT FK_PROD_DM_FILE_TAB40
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_TA57
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T55
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T54
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T45
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T46
/
ALTER TABLE PROD_DM_VERSION_TAB DROP CONSTRAINT FK_PROD_DM_VERSION_TAB36
/
ALTER TABLE PROD_DM_ORDER_TAB DROP CONSTRAINT FK_PROD_DM_ORDER_TAB59
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB56
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB51
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB44
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB53
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB52
/
DROP TABLE PROD_DM_CONTAINER_TAB
/
DROP TABLE PROD_DM_MARKUP_TAB
/
DROP TABLE PROD_DM_PHASE_CONTAINER_TAB
/
DROP TABLE PROD_DM_OPERATION_TAB
/
DROP TABLE PROD_DM_STRUCTDOC_TAB
/
DROP TABLE PROD_DM_FILE_TAB
/
DROP TABLE PROD_DM_DOCUMENT_TAB
/
DROP TABLE PROD_DM_FILESERVER_TAB
/
DROP TABLE PROD_DM_REQUEST_INFO_TAB
/
DROP TABLE PROD_DM_CHANGE_CONTENT_TAB
/
DROP TABLE PROD_DM_REFERENCE_TAB
/
DROP TABLE PROD_DM_VERSION_TAB
/
DROP TABLE PROD_DM_ORDER_TAB
/
DROP TABLE PROD_DM_CHANGE_INFO_TAB
/
DROP TABLE PROD_DM_PROF_CONTAINER_TAB
/
CREATE TABLE PROD_DM_CONTAINER_TAB (
	ContainerIID VARCHAR ( 255 ) NOT NULL,
	ContainerName VARCHAR ( 255 ) NOT NULL,
	ContainerTypeNo NUMERIC ( 7 ) NOT NULL,
	ProductIID VARCHAR ( 255 ),
	ContainerParentIID VARCHAR ( 255 ) NOT NULL,
	ContainerParentTypeNo NUMERIC ( 7 ) NOT NULL,
	ContainerOwnerIID VARCHAR ( 255 ) NOT NULL,
	ContainerOwnerName VARCHAR ( 255 ) NOT NULL,
	ContainerCreateTime NUMERIC ( 20 ) NOT NULL,
	ContainerModifyUserIID VARCHAR ( 255 ) NOT NULL,
	ContainerModifyUserName VARCHAR ( 255 ) NOT NULL,
	ContainerModifyTime NUMERIC ( 20 ) NOT NULL,
	ContainerDescription VARCHAR ( 511 ),
	ContainerLocation VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_CONTAINER_TAB14 PRIMARY KEY (ContainerIID)
	)
/
CREATE TABLE PROD_DM_MARKUP_TAB (
	MarkupIID VARCHAR ( 255 ) NOT NULL,
	MarkupName VARCHAR ( 255 ) NOT NULL,
	MarkupStorageId VARCHAR ( 255 ) NOT NULL,
	MarkupSize VARCHAR ( 255 ) NOT NULL,
	MarkupOwnerIID VARCHAR ( 255 ) NOT NULL,
	MarkupOwnerName VARCHAR ( 255 ) NOT NULL,
	MarkupCreateTime NUMERIC ( 20 ) NOT NULL,
	MarkupModifyTime NUMERIC ( 20 ) NOT NULL,
	MarkupType CHAR ( 20 ) NOT NULL,
	MarkupDescription VARCHAR ( 511 ),
	FileIID VARCHAR ( 255 ) NOT NULL,
	FileServerIID VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_MARKUP_TAB60 PRIMARY KEY (MarkupIID)
	)
/
CREATE TABLE PROD_DM_PHASE_CONTAINER_TAB (
	PhaseId VARCHAR ( 255 ) NOT NULL,
	DocumentLibrary NUMERIC ( 1 ) NOT NULL,
	ContainerIID VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_PHASE_CONTAINER_204 UNIQUE (ContainerIID, DocumentLibrary, PhaseId)
	)
/
CREATE TABLE PROD_DM_OPERATION_TAB (
	OperationIID VARCHAR ( 255 ) NOT NULL,
	ObjectIID VARCHAR ( 255 ) NOT NULL,
	ObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	OperationAction NUMERIC ( 1 ) NOT NULL,
	OperationUserIID VARCHAR ( 255 ) NOT NULL,
	OperationUserName VARCHAR ( 255 ) NOT NULL,
	OperationTime NUMERIC ( 20 ) NOT NULL,
	OperationDescription VARCHAR ( 511 ),
	CONSTRAINT PK_PROD_DM_OPERATION_TAB50 PRIMARY KEY (OperationIID)
	)
/
CREATE TABLE PROD_DM_STRUCTDOC_TAB (
	ObjectIID VARCHAR ( 255 ) NOT NULL,
	ObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	StructObjectIID VARCHAR ( 255 ) NOT NULL,
	StructObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	StructObjectGlobalId VARCHAR ( 255 ) NOT NULL,
	StructObjectProductIID VARCHAR ( 255 ) NOT NULL,
	StructDescription VARCHAR ( 511 ),
	CONSTRAINT PK_PROD_DM_STRUCTDOC_TAB52 PRIMARY KEY (ObjectIID, StructObjectGlobalId)
	)
/
CREATE TABLE PROD_DM_FILE_TAB (
	FileIID VARCHAR ( 255 ) NOT NULL,
	FileStorageId VARCHAR ( 255 ) NOT NULL,
	DocumentIID VARCHAR ( 255 ),
	VersionIID VARCHAR ( 255 ),
	FileOriginalName VARCHAR ( 255 ) NOT NULL,
	FileExtendName VARCHAR ( 127 ),
	FileSize VARCHAR ( 255 ) NOT NULL,
	FileCreateTime NUMERIC ( 20 ) NOT NULL,
	FileModifyTime NUMERIC ( 20 ) NOT NULL,
	IsMainFile NUMERIC ( 1 ) NOT NULL,
	IsCreateFromTemplate NUMERIC ( 1 ) NOT NULL,
	FileDescription VARCHAR ( 511 ),
	FileServerIID VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_FILE_TAB49 PRIMARY KEY (FileIID)
	)
/
CREATE TABLE PROD_DM_DOCUMENT_TAB (
	DocumentIID VARCHAR ( 255 ) NOT NULL,
	DocumentLibrary NUMERIC ( 1 ) NOT NULL,
	DocumentPIN VARCHAR ( 255 ) NOT NULL,
	DocumentName VARCHAR ( 255 ) NOT NULL,
	DocumentGlobalIID VARCHAR ( 255 ) NOT NULL,
	ProductIID VARCHAR ( 255 ) NOT NULL,
	DocumentTypeNo NUMERIC ( 7 ) NOT NULL,
	DocumentParentIID VARCHAR ( 255 ),
	DocumentParentTypeNo NUMERIC ( 7 ),
	DocumentPhase VARCHAR ( 255 ),
	DocumentProfession VARCHAR ( 255 ),
	DocumentSecret NUMERIC ( 7 ),
	DocumentOwnerIID VARCHAR ( 255 ) NOT NULL,
	DocumentOwnerName VARCHAR ( 255 ) NOT NULL,
	DocumentCreateTime NUMERIC ( 20 ) NOT NULL,
	DocumentModifyUserIID VARCHAR ( 255 ) NOT NULL,
	DocumentModifyUserName VARCHAR ( 255 ) NOT NULL,
	DocumentModifyTime NUMERIC ( 20 ) NOT NULL,
	DocumentStatus NUMERIC ( 1 ) NOT NULL,
	DocumentDepartment VARCHAR ( 255 ),
	IsLastDocument NUMERIC ( 1 ) NOT NULL,
	PublishVersionNo VARCHAR ( 7 ),
	DocumentDescription VARCHAR ( 255 ),
	RequestOrderIID VARCHAR ( 255 ),
	ChangeOrderIID VARCHAR ( 255 ),
	CONSTRAINT PK_PROD_DM_DOCUMENT_TAB48 PRIMARY KEY (DocumentIID)
	)
/
CREATE TABLE PROD_DM_FILESERVER_TAB (
	FileServerIID VARCHAR ( 255 ) NOT NULL,
	FileServerIP VARCHAR ( 255 ) NOT NULL,
	FileServerPort CHAR ( 8 ),
	ProductIID VARCHAR ( 255 ) NOT NULL,
	Library NUMERIC ( 1 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_FILESERVER_TAB282 UNIQUE (Library, ProductIID),
	CONSTRAINT PK_PROD_DM_FILESERVER_TAB61 PRIMARY KEY (FileServerIID)
	)
/
CREATE TABLE PROD_DM_REQUEST_INFO_TAB (
	OrderIID VARCHAR ( 255 ) NOT NULL,
	ObjectIID VARCHAR ( 255 ) NOT NULL,
	ObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	ObjectGlobalIID VARCHAR ( 255 ),
	ChangeContent VARCHAR ( 255 ) NOT NULL,
	ChangeReason VARCHAR ( 255 ) NOT NULL,
	EffectAnalysis VARCHAR ( 255 ) NOT NULL,
	InterfaceAnalysis VARCHAR ( 255 ) NOT NULL,
	Remark VARCHAR ( 511 ),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA280 UNIQUE (InterfaceAnalysis),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA279 UNIQUE (ChangeReason),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA277 UNIQUE (ChangeContent),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA278 UNIQUE (EffectAnalysis),
	CONSTRAINT PK_PROD_DM_REQUEST_INFO_T64 PRIMARY KEY (OrderIID, ObjectIID)
	)
/
CREATE TABLE PROD_DM_CHANGE_CONTENT_TAB (
	ContentIID VARCHAR ( 255 ) NOT NULL,
	ContentDescription VARCHAR ( 511 ),
	CONSTRAINT PK_PROD_DM_CHANGE_CONTENT_T63 PRIMARY KEY (ContentIID)
	)
/
CREATE TABLE PROD_DM_REFERENCE_TAB (
	ObjectIID VARCHAR ( 255 ) NOT NULL,
	ObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	RefObjectIID VARCHAR ( 255 ) NOT NULL,
	RefObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	RefObjectGlobalId VARCHAR ( 255 ) NOT NULL,
	RefObjectProductIID VARCHAR ( 255 ) NOT NULL,
	RefDescription VARCHAR ( 511 ),
	CONSTRAINT PK_PROD_DM_REFERENCE_TAB51 PRIMARY KEY (ObjectIID, RefObjectGlobalId),
	CONSTRAINT TC_PROD_DM_REFERENCE_TAB206 UNIQUE (RefObjectGlobalId, ObjectIID)
	)
/
CREATE TABLE PROD_DM_VERSION_TAB (
	VersionIID VARCHAR ( 255 ) NOT NULL,
	VersionTypeNo NUMERIC ( 7 ) NOT NULL,
	VersionNo VARCHAR ( 10 ) NOT NULL,
	DocumentIID VARCHAR ( 255 ) NOT NULL,
	ParentVersionIID VARCHAR ( 255 ),
	ParentVersionNo VARCHAR ( 10 ),
	VersionOwnerIID VARCHAR ( 255 ) NOT NULL,
	VersionOwnerName VARCHAR ( 255 ) NOT NULL,
	VersionCreateTime NUMERIC ( 20 ) NOT NULL,
	VersionModifyUserIID VARCHAR ( 255 ) NOT NULL,
	VersionModifyUserName VARCHAR ( 255 ) NOT NULL,
	VersionModifyTime NUMERIC ( 20 ) NOT NULL,
	VersionActiveState NUMERIC ( 1 ) NOT NULL,
	VersionLockState NUMERIC ( 1 ) NOT NULL,
	VersionHistoryState NUMERIC ( 1 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_VERSION_TAB58 PRIMARY KEY (VersionIID)
	)
/
CREATE TABLE PROD_DM_ORDER_TAB (
	OrderIID VARCHAR ( 255 ) NOT NULL,
	OrderId VARCHAR ( 255 ) NOT NULL,
	OrderName VARCHAR ( 255 ) NOT NULL,
	OrderType NUMERIC ( 7 ) NOT NULL,
	OrderState NUMERIC ( 1 ) NOT NULL,
	OrderOwnerIID VARCHAR ( 255 ) NOT NULL,
	OrderOwnerName VARCHAR ( 255 ) NOT NULL,
	OrderCreateTime NUMERIC ( 20 ) NOT NULL,
	ProductIID VARCHAR ( 255 ) NOT NULL,
	ContentIID VARCHAR ( 255 ) NOT NULL,
	Description VARCHAR ( 511 ) ,
	CONSTRAINT TC_PROD_DM_ORDER_TAB288 UNIQUE (ContentIID),
	CONSTRAINT PK_PROD_DM_ORDER_TAB65 PRIMARY KEY (OrderIID)
	)
/
CREATE TABLE PROD_DM_CHANGE_INFO_TAB (
	OrderIID VARCHAR ( 255 ) NOT NULL,
	ChangeObjectIID VARCHAR ( 255 ) NOT NULL,
	ChangeObjectTypeNo NUMERIC ( 7 ) NOT NULL,
	ChangeObjectGlobalIID VARCHAR ( 255 ),
	ModifyObjectIID VARCHAR ( 255 ) NOT NULL,
	ModifyObjectTypeNo NUMERIC ( 7 ),
	NewObjectIID VARCHAR ( 255 ),
	NewObjectTypeNo NUMERIC ( 7 ),
	BeforeChangeContent VARCHAR ( 255 ) NOT NULL,
	AfterChangeContent VARCHAR ( 255 ) NOT NULL,
	ChangeType NUMERIC ( 1 ) NOT NULL,
	ChangeReason VARCHAR ( 255 ) NOT NULL,
	DisposalOpinion VARCHAR ( 255 ) NOT NULL,
	ImplementTime NUMERIC ( 20 ),
	Remark VARCHAR ( 511 ),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB283 UNIQUE (NewObjectIID),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB273 UNIQUE (AfterChangeContent),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB272 UNIQUE (DisposalOpinion),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB274 UNIQUE (BeforeChangeContent),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB275 UNIQUE (ChangeReason),
	CONSTRAINT PK_SYS_DM_CHANGEINFO_TAB62 PRIMARY KEY (OrderIID, ChangeObjectIID)
	)
/
CREATE TABLE PROD_DM_PROF_CONTAINER_TAB (
	PhaseId VARCHAR ( 255 ),
	ProfessionIID VARCHAR ( 255 ) NOT NULL,
	DocumentLibrary NUMERIC ( 1 ) NOT NULL,
	ContainerIID VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_PROF_CONTAINER_T202 UNIQUE (ContainerIID, DocumentLibrary)
	)
/
ALTER TABLE PROD_DM_MARKUP_TAB ADD CONSTRAINT FK_PROD_DM_MARKUP_TAB38 FOREIGN KEY (FileServerIID) REFERENCES PROD_DM_FILESERVER_TAB (FileServerIID)
/
ALTER TABLE PROD_DM_MARKUP_TAB ADD CONSTRAINT FK_PROD_DM_MARKUP_TAB37 FOREIGN KEY (FileIID) REFERENCES PROD_DM_FILE_TAB (FileIID)
/
ALTER TABLE PROD_DM_FILE_TAB ADD CONSTRAINT FK_PROD_DM_FILE_TAB40 FOREIGN KEY (FileServerIID) REFERENCES PROD_DM_FILESERVER_TAB (FileServerIID)
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD CONSTRAINT FK_PROD_DM_REQUEST_INFO_TA57 FOREIGN KEY (OrderIID) REFERENCES PROD_DM_ORDER_TAB (OrderIID)
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD CONSTRAINT FK_PROD_DM_REQUEST_INFO_T55 FOREIGN KEY (InterfaceAnalysis) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD CONSTRAINT FK_PROD_DM_REQUEST_INFO_T54 FOREIGN KEY (ChangeReason) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD CONSTRAINT FK_PROD_DM_REQUEST_INFO_T45 FOREIGN KEY (ChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD CONSTRAINT FK_PROD_DM_REQUEST_INFO_T46 FOREIGN KEY (EffectAnalysis) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_VERSION_TAB ADD CONSTRAINT FK_PROD_DM_VERSION_TAB36 FOREIGN KEY (DocumentIID) REFERENCES PROD_DM_DOCUMENT_TAB (DocumentIID)
/
ALTER TABLE PROD_DM_ORDER_TAB ADD CONSTRAINT FK_PROD_DM_ORDER_TAB59 FOREIGN KEY (ContentIID) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB56 FOREIGN KEY (OrderIID) REFERENCES PROD_DM_ORDER_TAB (OrderIID)
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB51 FOREIGN KEY (BeforeChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB44 FOREIGN KEY (AfterChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB53 FOREIGN KEY (DisposalOpinion) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB52 FOREIGN KEY (ChangeReason) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID)
/
