ALTER TABLE PROD_DM_MARKUP_TAB DROP CONSTRAINT FK_PROD_DM_MARKUP_TAB38
/
ALTER TABLE PROD_DM_MARKUP_TAB DROP CONSTRAINT FK_PROD_DM_MARKUP_TAB37
/
ALTER TABLE PROD_DM_FILE_TAB DROP CONSTRAINT FK_PROD_DM_FILE_TAB40
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_TA57
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T55
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T54
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T45
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB DROP CONSTRAINT FK_PROD_DM_REQUEST_INFO_T46
/
ALTER TABLE PROD_DM_VERSION_TAB DROP CONSTRAINT FK_PROD_DM_VERSION_TAB36
/
ALTER TABLE PROD_DM_ORDER_TAB DROP CONSTRAINT FK_PROD_DM_ORDER_TAB59
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB56
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB51
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB44
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB53
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB DROP CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB52
/
DROP TABLE PROD_DM_CONTAINER_TAB
/
DROP TABLE PROD_DM_MARKUP_TAB
/
DROP TABLE PROD_DM_PHASE_CONTAINER_TAB
/
DROP TABLE PROD_DM_OPERATION_TAB
/
DROP TABLE PROD_DM_STRUCTDOC_TAB
/
DROP TABLE PROD_DM_FILE_TAB
/
DROP TABLE PROD_DM_DOCUMENT_TAB
/
DROP TABLE PROD_DM_FILESERVER_TAB
/
DROP TABLE PROD_DM_REQUEST_INFO_TAB
/
DROP TABLE PROD_DM_CHANGE_CONTENT_TAB
/
DROP TABLE PROD_DM_REFERENCE_TAB
/
DROP TABLE PROD_DM_VERSION_TAB
/
DROP TABLE PROD_DM_ORDER_TAB
/
DROP TABLE PROD_DM_CHANGE_INFO_TAB
/
DROP TABLE PROD_DM_PROF_CONTAINER_TAB
/
CREATE TABLE PROD_DM_CONTAINER_TAB (
	ContainerIID VARCHAR2 ( 255 ) NOT NULL,
	ContainerName VARCHAR2 ( 255 ) NOT NULL,
	ContainerTypeNo NUMBER ( 7 ) NOT NULL,
	ProductIID VARCHAR2 ( 255 ),
	ContainerParentIID VARCHAR2 ( 255 ) NOT NULL,
	ContainerParentTypeNo NUMBER ( 7 ) NOT NULL,
	ContainerOwnerIID VARCHAR2 ( 255 ) NOT NULL,
	ContainerOwnerName VARCHAR2 ( 255 ) NOT NULL,
	ContainerCreateTime NUMBER ( 20 ) NOT NULL,
	ContainerModifyUserIID VARCHAR2 ( 255 ) NOT NULL,
	ContainerModifyUserName VARCHAR2 ( 255 ) NOT NULL,
	ContainerModifyTime NUMBER ( 20 ) NOT NULL,
	ContainerDescription VARCHAR2 ( 511 ),
	ContainerLocation VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_CONTAINER_TAB14 PRIMARY KEY (ContainerIID)
	)
/
CREATE TABLE PROD_DM_MARKUP_TAB (
	MarkupIID VARCHAR2 ( 255 ) NOT NULL,
	MarkupName VARCHAR2 ( 255 ) NOT NULL,
	MarkupStorageId VARCHAR2 ( 255 ) NOT NULL,
	MarkupSize VARCHAR2 ( 255 ) NOT NULL,
	MarkupOwnerIID VARCHAR2 ( 255 ) NOT NULL,
	MarkupOwnerName VARCHAR2 ( 255 ) NOT NULL,
	MarkupCreateTime NUMBER ( 20 ) NOT NULL,
	MarkupModifyTime NUMBER ( 20 ) NOT NULL,
	MarkupType CHAR ( 20 ) NOT NULL,
	MarkupDescription VARCHAR2 ( 511 ),
	FileIID VARCHAR2 ( 255 ) NOT NULL,
	FileServerIID VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_MARKUP_TAB60 PRIMARY KEY (MarkupIID)
	)
/
CREATE TABLE PROD_DM_PHASE_CONTAINER_TAB (
	PhaseId VARCHAR2 ( 255 ) NOT NULL,
	DocumentLibrary NUMBER ( 1 ) NOT NULL,
	ContainerIID VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_PHASE_CONTAINER_204 UNIQUE (ContainerIID, DocumentLibrary, PhaseId)
	)
/
CREATE TABLE PROD_DM_OPERATION_TAB (
	OperationIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectTypeNo NUMBER ( 7 ) NOT NULL,
	OperationAction NUMBER ( 1 ) NOT NULL,
	OperationUserIID VARCHAR2 ( 255 ) NOT NULL,
	OperationUserName VARCHAR2 ( 255 ) NOT NULL,
	OperationTime NUMBER ( 20 ) NOT NULL,
	OperationDescription VARCHAR2 ( 511 ),
	CONSTRAINT PK_PROD_DM_OPERATION_TAB50 PRIMARY KEY (OperationIID)
	)
/
CREATE TABLE PROD_DM_STRUCTDOC_TAB (
	ObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectTypeNo NUMBER ( 7 ) NOT NULL,
	StructObjectIID VARCHAR2 ( 255 ) NOT NULL,
	StructObjectTypeNo NUMBER ( 7 ) NOT NULL,
	StructObjectGlobalId VARCHAR2 ( 255 ) NOT NULL,
	StructObjectProductIID VARCHAR2 ( 255 ) NOT NULL,
	StructDescription VARCHAR2 ( 511 ),
	CONSTRAINT PK_PROD_DM_STRUCTDOC_TAB52 PRIMARY KEY (ObjectIID, StructObjectGlobalId)
	)
/
CREATE TABLE PROD_DM_FILE_TAB (
	FileIID VARCHAR2 ( 255 ) NOT NULL,
	FileStorageId VARCHAR2 ( 255 ) NOT NULL,
	DocumentIID VARCHAR2 ( 255 ),
	VersionIID VARCHAR2 ( 255 ),
	FileOriginalName VARCHAR2 ( 255 ) NOT NULL,
	FileExtendName VARCHAR2 ( 127 ),
	FileSize VARCHAR2 ( 255 ) NOT NULL,
	FileCreateTime NUMBER ( 20 ) NOT NULL,
	FileModifyTime NUMBER ( 20 ) NOT NULL,
	IsMainFile NUMBER ( 1 ) NOT NULL,
	IsCreateFromTemplate NUMBER ( 1 ) NOT NULL,
	FileDescription VARCHAR2 ( 511 ),
	FileServerIID VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_FILE_TAB49 PRIMARY KEY (FileIID)
	)
/
CREATE TABLE PROD_DM_DOCUMENT_TAB (
	DocumentIID VARCHAR2 ( 255 ) NOT NULL,
	DocumentLibrary NUMBER ( 1 ) NOT NULL,
	DocumentPIN VARCHAR2 ( 255 ) NOT NULL,
	DocumentName VARCHAR2 ( 255 ) NOT NULL,
	DocumentGlobalIID VARCHAR2 ( 255 ) NOT NULL,
	ProductIID VARCHAR2 ( 255 ) NOT NULL,
	DocumentTypeNo NUMBER ( 7 ) NOT NULL,
	DocumentParentIID VARCHAR2 ( 255 ),
	DocumentParentTypeNo NUMBER ( 7 ),
	DocumentPhase VARCHAR2 ( 255 ),
	DocumentProfession VARCHAR2 ( 255 ),
	DocumentSecret NUMBER ( 7 ),
	DocumentOwnerIID VARCHAR2 ( 255 ) NOT NULL,
	DocumentOwnerName VARCHAR2 ( 255 ) NOT NULL,
	DocumentCreateTime NUMBER ( 20 ) NOT NULL,
	DocumentModifyUserIID VARCHAR2 ( 255 ) NOT NULL,
	DocumentModifyUserName VARCHAR2 ( 255 ) NOT NULL,
	DocumentModifyTime NUMBER ( 20 ) NOT NULL,
	DocumentStatus NUMBER ( 1 ) NOT NULL,
	DocumentDepartment VARCHAR2 ( 255 ),
	IsLastDocument NUMBER ( 1 ) NOT NULL,
	PublishVersionNo VARCHAR2 ( 7 ),
	DocumentDescription VARCHAR2 ( 255 ),
	RequestOrderIID VARCHAR2 ( 255 ),
	ChangeOrderIID VARCHAR2 ( 255 ),
	CONSTRAINT PK_PROD_DM_DOCUMENT_TAB48 PRIMARY KEY (DocumentIID)
	)
/
CREATE TABLE PROD_DM_FILESERVER_TAB (
	FileServerIID VARCHAR2 ( 255 ) NOT NULL,
	FileServerIP VARCHAR2 ( 255 ) NOT NULL,
	FileServerPort CHAR ( 8 ),
	ProductIID VARCHAR2 ( 255 ) NOT NULL,
	Library NUMBER ( 1 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_FILESERVER_TAB282 UNIQUE (Library, ProductIID),
	CONSTRAINT PK_PROD_DM_FILESERVER_TAB61 PRIMARY KEY (FileServerIID)
	)
/
CREATE TABLE PROD_DM_REQUEST_INFO_TAB (
	OrderIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectTypeNo NUMBER ( 7 ) NOT NULL,
	ObjectGlobalIID VARCHAR2 ( 255 ),
	ChangeContent VARCHAR2 ( 255 ) NOT NULL,
	ChangeReason VARCHAR2 ( 255 ) NOT NULL,
	EffectAnalysis VARCHAR2 ( 255 ) NOT NULL,
	InterfaceAnalysis VARCHAR2 ( 255 ) NOT NULL,
	Remark VARCHAR2 ( 511 ),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA280 UNIQUE (InterfaceAnalysis),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA279 UNIQUE (ChangeReason),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA277 UNIQUE (ChangeContent),
	CONSTRAINT TC_PROD_DM_REQUEST_INFO_TA278 UNIQUE (EffectAnalysis),
	CONSTRAINT PK_PROD_DM_REQUEST_INFO_T64 PRIMARY KEY (OrderIID, ObjectIID)
	)
/
CREATE TABLE PROD_DM_CHANGE_CONTENT_TAB (
	ContentIID VARCHAR2 ( 255 ) NOT NULL,
	ContentDescription VARCHAR2 ( 511 ),
	CONSTRAINT PK_PROD_DM_CHANGE_CONTENT_T63 PRIMARY KEY (ContentIID)
	)
/
CREATE TABLE PROD_DM_REFERENCE_TAB (
	ObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ObjectTypeNo NUMBER ( 7 ) NOT NULL,
	RefObjectIID VARCHAR2 ( 255 ) NOT NULL,
	RefObjectTypeNo NUMBER ( 7 ) NOT NULL,
	RefObjectGlobalId VARCHAR2 ( 255 ) NOT NULL,
	RefObjectProductIID VARCHAR2 ( 255 ) NOT NULL,
	RefDescription VARCHAR2 ( 511 ),
	CONSTRAINT PK_PROD_DM_REFERENCE_TAB51 PRIMARY KEY (ObjectIID, RefObjectGlobalId),
	CONSTRAINT TC_PROD_DM_REFERENCE_TAB206 UNIQUE (RefObjectGlobalId, ObjectIID)
	)
/
CREATE TABLE PROD_DM_VERSION_TAB (
	VersionIID VARCHAR2 ( 255 ) NOT NULL,
	VersionTypeNo NUMBER ( 7 ) NOT NULL,
	VersionNo VARCHAR2 ( 10 ) NOT NULL,
	DocumentIID VARCHAR2 ( 255 ) NOT NULL,
	ParentVersionIID VARCHAR2 ( 255 ),
	ParentVersionNo VARCHAR2 ( 10 ),
	VersionOwnerIID VARCHAR2 ( 255 ) NOT NULL,
	VersionOwnerName VARCHAR2 ( 255 ) NOT NULL,
	VersionCreateTime NUMBER ( 20 ) NOT NULL,
	VersionModifyUserIID VARCHAR2 ( 255 ) NOT NULL,
	VersionModifyUserName VARCHAR2 ( 255 ) NOT NULL,
	VersionModifyTime NUMBER ( 20 ) NOT NULL,
	VersionActiveState NUMBER ( 1 ) NOT NULL,
	VersionLockState NUMBER ( 1 ) NOT NULL,
	VersionHistoryState NUMBER ( 1 ) NOT NULL,
	CONSTRAINT PK_PROD_DM_VERSION_TAB58 PRIMARY KEY (VersionIID)
	)
/
CREATE TABLE PROD_DM_ORDER_TAB (
	OrderIID VARCHAR2 ( 255 ) NOT NULL,
	OrderId VARCHAR2 ( 255 ) NOT NULL,
	OrderName VARCHAR2 ( 255 ) NOT NULL,
	OrderType NUMBER ( 7 ) NOT NULL,
	OrderState NUMBER ( 1 ) NOT NULL,
	OrderOwnerIID VARCHAR2 ( 255 ) NOT NULL,
	OrderOwnerName VARCHAR2 ( 255 ) NOT NULL,
	OrderCreateTime NUMBER ( 20 ) NOT NULL,
	ProductIID VARCHAR2 ( 255 ) NOT NULL,
	ContentIID VARCHAR2 ( 255 ) NOT NULL,
	Description VARCHAR2 ( 511 ) ,
	CONSTRAINT TC_PROD_DM_ORDER_TAB288 UNIQUE (ContentIID),
	CONSTRAINT PK_PROD_DM_ORDER_TAB65 PRIMARY KEY (OrderIID)
	)
/
CREATE TABLE PROD_DM_CHANGE_INFO_TAB (
	OrderIID VARCHAR2 ( 255 ) NOT NULL,
	ChangeObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ChangeObjectTypeNo NUMBER ( 7 ) NOT NULL,
	ChangeObjectGlobalIID VARCHAR2 ( 255 ),
	ModifyObjectIID VARCHAR2 ( 255 ) NOT NULL,
	ModifyObjectTypeNo NUMBER ( 7 ),
	NewObjectIID VARCHAR2 ( 255 ),
	NewObjectTypeNo NUMBER ( 7 ),
	BeforeChangeContent VARCHAR2 ( 255 ) NOT NULL,
	AfterChangeContent VARCHAR2 ( 255 ) NOT NULL,
	ChangeType NUMBER ( 1 ) NOT NULL,
	ChangeReason VARCHAR2 ( 255 ) NOT NULL,
	DisposalOpinion VARCHAR2 ( 255 ) NOT NULL,
	ImplementTime NUMBER ( 20 ),
	Remark VARCHAR2 ( 511 ),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB283 UNIQUE (NewObjectIID),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB273 UNIQUE (AfterChangeContent),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB272 UNIQUE (DisposalOpinion),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB274 UNIQUE (BeforeChangeContent),
	CONSTRAINT TC_PROD_DM_CHANGE_INFO_TAB275 UNIQUE (ChangeReason),
	CONSTRAINT PK_SYS_DM_CHANGEINFO_TAB62 PRIMARY KEY (OrderIID, ChangeObjectIID)
	)
/
CREATE TABLE PROD_DM_PROF_CONTAINER_TAB (
	PhaseId VARCHAR2 ( 255 ),
	ProfessionIID VARCHAR2 ( 255 ) NOT NULL,
	DocumentLibrary NUMBER ( 1 ) NOT NULL,
	ContainerIID VARCHAR2 ( 255 ) NOT NULL,
	CONSTRAINT TC_PROD_DM_PROF_CONTAINER_T202 UNIQUE (ContainerIID, DocumentLibrary)
	)
/
ALTER TABLE PROD_DM_MARKUP_TAB ADD ( CONSTRAINT FK_PROD_DM_MARKUP_TAB38 FOREIGN KEY (FileServerIID) REFERENCES PROD_DM_FILESERVER_TAB (FileServerIID))
/
ALTER TABLE PROD_DM_MARKUP_TAB ADD ( CONSTRAINT FK_PROD_DM_MARKUP_TAB37 FOREIGN KEY (FileIID) REFERENCES PROD_DM_FILE_TAB (FileIID))
/
ALTER TABLE PROD_DM_FILE_TAB ADD ( CONSTRAINT FK_PROD_DM_FILE_TAB40 FOREIGN KEY (FileServerIID) REFERENCES PROD_DM_FILESERVER_TAB (FileServerIID))
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_REQUEST_INFO_TA57 FOREIGN KEY (OrderIID) REFERENCES PROD_DM_ORDER_TAB (OrderIID))
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_REQUEST_INFO_T55 FOREIGN KEY (InterfaceAnalysis) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_REQUEST_INFO_T54 FOREIGN KEY (ChangeReason) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_REQUEST_INFO_T45 FOREIGN KEY (ChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_REQUEST_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_REQUEST_INFO_T46 FOREIGN KEY (EffectAnalysis) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_VERSION_TAB ADD ( CONSTRAINT FK_PROD_DM_VERSION_TAB36 FOREIGN KEY (DocumentIID) REFERENCES PROD_DM_DOCUMENT_TAB (DocumentIID))
/
ALTER TABLE PROD_DM_ORDER_TAB ADD ( CONSTRAINT FK_PROD_DM_ORDER_TAB59 FOREIGN KEY (ContentIID) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB56 FOREIGN KEY (OrderIID) REFERENCES PROD_DM_ORDER_TAB (OrderIID))
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB51 FOREIGN KEY (BeforeChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB44 FOREIGN KEY (AfterChangeContent) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB53 FOREIGN KEY (DisposalOpinion) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
ALTER TABLE PROD_DM_CHANGE_INFO_TAB ADD ( CONSTRAINT FK_PROD_DM_CHANGE_INFO_TAB52 FOREIGN KEY (ChangeReason) REFERENCES PROD_DM_CHANGE_CONTENT_TAB (ContentIID))
/
